apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: screentwo
  name: screentwo
  namespace: openshift-monitoring
spec:
  endpoints:
    - interval: 2m
      port: prom
      scrapeTimeout: 2m
    - interval1: 30s
      port: http1
  namespaceSelector:
    matchNames:
    - smartscreenone-dev-app
    - smartscreenone-devops-app
    
  selector:
    matchLabels:
      app: screentwo